### ISSUE TITLE
Issue with generated regexes

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/progenitor#132]
With the regex changes to the nexus.json file introduced in https://github.com/oxidecomputer/omicron/pull/1414, the client code generated by progenitor fails to decode the response body even if the value is valid.

I noticed this specifically with the Ipv6Net struct. 

### On read
When I try to list VPCs the response I get is: 

```console
Invalid Response Payload: error decoding response body: doesn't match pattern "^([fF][dD])[0-9a-fA-F]{2}:(([0-9a-fA-F]{1,4}:){6}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,6}:)\/(6[4-9]|[7-9][0-9]|1[0-1][0-9]|12[0-6])$"
```

The only VPC is the default VPC that comes preinstalled which has a valid value `fd5a:1607:69ee::/48`.

### On write
When I try to create a VPC without defining an IPv6 prefix, and letting Omicron set a default one, the response I get is the same as the one on read.

When I try to create a VPC defining an IPv6 prefix using either the example from the spec `fd12:3456::/64` the response I get is 

```console
status: 400 Bad Request; message: VPC IPv6 address prefixes must be in the Unique Local Address range `fd00::/48` (RFD 4193)
```

So I tried another IPv6 prefix within that range `fd12:3456::/48` and got the original error:

```console
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "doesn't match pattern \"^([fF][dD])[0-9a-fA-F]{2}:(([0-9a-fA-F]{1,4}:){6}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,6}:)\\/(6[4-9]|[7-9][0-9]|1[0-1][0-9]|12[0-6])$\""'
```

I dug around for a while on where to fix this, but got a bit lost unfortunately.

**Comment by ahl** [comment]
It looks like the regex both before and after oxidecomputer/omicron#1414 would not match a `/48`. The difference is that previously we were doing no validation.

This seems like a problem with a regex and another problem with docs.

As a workaround, you could try changing the `pattern` for `Ipv6Net` in the OpenAPI doc to allow `/48`.

We should also look into returning the actual response body in the `Error::InvalidResponsePayload` to make debugging this easier.

**Comment by karencfv** [comment]
ha! Thanks, fix here https://github.com/oxidecomputer/omicron/pull/1460 :)

**Comment by karencfv** [comment]
Closing issue as this is not related to progenitor
