### ISSUE TITLE
Comparison with other generator

### ISSUE THREAD

**Issue by dsisnero** [oxidecomputer/progenitor#181]
I see you have https://github.com/oxidecomputer/third-party-api-clients which is used to generate your api-clients.  This uses a generate  module in the repo.  

What is the difference between this progenitor and the generation of clients within the above repo.

Thanks

**Comment by ahl** [comment]
The generator in that repo started as a primordial fork of progenitor. On one hand, it has failed to benefit from approximately 98% of the work that's gone into progenitor/typify; on the other hand, it's grown quite a few very very very special cases to handle various APIs. Our general advice would be to prefer progenitor and to file bugs if and when you encounter OpenAPI documents with unsupported structures or whose generated code could be improved.
