### ISSUE TITLE
handle tags

### ISSUE THREAD

**Issue by ahl** [oxidecomputer/progenitor#23]
Tags are a useful mechanism to group like-items to make them more easily found in particular in the generated documentation.
There are several ways we could handle tags on operations:

1. Clients could have sub-objects that correspond to the tag
```rust
    client.instances.instance_start(...);
```

2. We could have a trait for each tag that defines some methods:
```rust
    use the_crate::ClientInstancesExt;
    client.instances_instance_start(...);
```

3. We could change things more significantly along the lines of the rust Stripe API, i.e. make the client a dumb container rather than the thing with all the methods:
```rust
    let client = Client::new(...);
    Instances::instance_start(&client, ...);
```

... and I'm sure there are others.

I think my preference is for 2 since it makes the docs easy to navigate and lets you tab complete everything from `client.<tab>` without knowing which tags happen to apply.

**Comment by jclulow** [comment]
I'm not sure how to get here, but I think what I'd really like to be able to achieve somehow is removing all of the redundant strings from the names of things.  For example, I'd much prefer to have a client that allowed:

```rust
client.instance.start(id).await?;
client.instance.stop(id).await?;
let workers = client.factory.workers().await?;
```

In the Dropshot server I'd probably call these `instance_stop` and `instance_start` with the `instance` tag, and `factory_workers` with the `factory` tag.  Perhaps there'd be some metadata to add to the document to say "strip tag as a prefix from endpoint names".  Perhaps it'd be a client generator flag one could opt into.

A background question I have is: do endpoint names have to be unique on their own (i.e., ignoring tags) or is the namespace actually (tag, instance) as a tuple?  Proposal 2 makes the method name really long, but maybe we should be avoiding using the prefix explicitly in the actual endpoint name if the tag is considered part of the ID of an endpoint?

**Comment by ahl** [comment]
After pursuing 2, I came to the conclusion that it's not a great solution. In particular it requires the use of `async` in traits which is sort of possible with `#[async_trait]` but the resulting rustdoc output is atrocious and confusing. Since having clean, comprehensible docs is part of the goal here, this is a significant deficiency. The short of it is that `#[async_trait]` effectively desugars `async` to return a `Pin<Box<dyn std::future::Future<Output = XXX> + Send + 'some_lifetime>>` which is all fine, but makes for ugly ugly docs.

A related alternative, however, might be to implement a more significant change: move from positional arguments to more of a builder pattern:

```rust
client
    .project_instances_instance_start()
    .instance_name("my_instance")
    .organization_name("my_org")
    .project_name("my_project")
    .execute()
    .await?;
```

In this case, `fn project_instances_instance_start(&self)` (which could be in an Ext trait) would return something like `ProjectInstancesInstanceStartBuilder` with methods for parameters and an `async fn execute(self)` method. Mandatory parameters could produce a new Error variant.

**Comment by ahl** [comment]
While handling of tags and the style of the generated code may seem separable, they choices impact each other.

In response to some specific suggestions above:
1. I think it is a valuable property to have the names of methods be the `operation_id` in whole, that is to say, not manipulating those strings or making assumptions about their constructions. If that proves too limiting, my suggestion is to add extensions to the OpenAPI document that provide guidance regarding the names of methods.
2. I agree that the builder pattern seems like a better approach and the AWS SDK has nice attributes.
3. I like the idea of baking in client-wide defaults; what would we do for operations that don't allow those parameters? Ignore the parameters? Prohibit the use of those interfaces?

**Comment by jclulow** [comment]
> I like the idea of baking in client-wide defaults; what would we do for operations that don't allow those parameters? Ignore the parameters? Prohibit the use of those interfaces?

That's a good question.  I suspect ignoring the parameters will probably result in the most ergonomic client, at least from the perspective of not having to have a different defaults object/type for each combination of options.  But we would I think then want to carefully curate which options we'll allow as defaults, to make understanding the way it works reasonably easy -- and to make holding it wrong relatively benign.

**Comment by jclulow** [comment]
Probably there are other things to think about like what to do if there are two options that sort of conflict; e.g., if we allow a project to be referred to by both user-select Name and some system-provided ID.  Also, we'd have to be ruthless (through the use of lint?) in ensuring that, say, the `project_name` was defined and used the same way uniformly throughout our API.

**Comment by karencfv** [comment]
This is great! I really like the idea of leveraging tags to help generate documentation without making the generators do the heavy lifting.

> Also, we'd have to be ruthless (through the use of lint?) in ensuring that, say, the project_name parameter was defined and used the same way uniformly throughout our API.

I heavily support the idea of using the linter to ensure this.

**Comment by ahl** [comment]
Closing this as tags are handled for the builder style interface.
