### ISSUE TITLE
Why does this tool generate `Hashmap<String, serde_json::Value>` so liberally?

### ISSUE THREAD

**Issue by jsenkpiel-godaddy** [oxidecomputer/progenitor#361]
`Hashmap<String, serde_json::Value>` is particularly annoying to work with from a library, since it doesn't really interact nicely with `serde_json::Value` itself.

It seem like generating `serde_json::Map<String, Value>` or probably just `serde_json::Value` would be better for the interests of an average user in a generic "how this interacts with the other libraries in question" sense.

Currently my code is having to `.into_iter().collect()` or `.iter().cloned().collect()` multiple times to go between these two...

_Edit, whoops, wasn't supposed to be from this GH account. Oh well._

**Comment by jsenkpiel-godaddy** [comment]
Also this is made worse by the desire to `serde_json::from_value()` from a response returned by a progenitor backed library, which is particularly annoying from a `HashMap<String, Value>` as well.

**Comment by jclulow** [comment]
I agree that it would be a lot easier to use `serde_json::from_value()` for weakly typed portions of a response body if we used a straight `serde_json::Value` in places where we currently use a `Hashmap<String, serde_json::Value>` today.

**Comment by ahl** [comment]
@jsenkpiel-godaddy can you share an example of the input OpenAPI document or the output code? The situation where I typically see `Hashmap<String, serde_json::Value>` output is for schemas like this:

```json
{
  "type": "object",
  "additionalProperties": true
}
```

Switching to `serde_json::Map<String, Value>` seems like a nice improvement although I'm not sure I'd want to use `serde_json::Map` for other `V` types e.g. for a schema like

```json
{
  "type": "object",
  "additionalProperties": {
    "$ref": "#/components/schemas/Something"
  }
}
```


Using `serde_json::Value` seems like it loses precision which I've been reluctant to do so far.

**Comment by jsenkpiel-godaddy** [comment]
Ultimately, I have the following OpenAPI:
```JSON
      "SettingRules": {
        "oneOf": [
          {
            "$ref": "#components/schemas/StaticValueRule"
          },
          {
            "$ref": "#components/schemas/ConditionalValueRuleset"
          }
        ]
      },
      "StaticValueRule": {
        "type": "object",
        "required": [
          "value"
        ],
        "properties": {
          "value": {
            "oneOf": [
              {
                "$ref": "#components/schemas/StaticStr"
              },
              {
                "$ref": "#components/schemas/StaticNum"
              },
              {
                "$ref": "#components/schemas/StaticBool"
              },
              {
                "$ref": "#components/schemas/StaticArr"
              },
              {
                "$ref": "#components/schemas/StaticObj"
              }
            ]
          }
        }
      },
      "StaticStr": {
        "type": "string"
      },
      "StaticNum": {
        "type": "number"
      },
      "StaticBool": {
        "type": "boolean"
      },
      "StaticArr": {
        "type": "array"
      },
      "StaticObj": {
        "type": "object"
      },
```

Which ends up producing this code, which is the problematic type in question:

```rust
    #[derive(Clone, Debug, Deserialize, Serialize)]
    pub struct StaticValueRule {
        pub value: StaticValueRuleValue,
    }

    #[derive(Clone, Debug, Deserialize, Serialize)]
    #[serde(untagged)]
    pub enum StaticValueRuleValue {
        Str(StaticStr),
        Num(StaticNum),
        Bool(StaticBool),
        Arr(StaticArr),
        Obj(StaticObj),
    }
    
    #[derive(Clone, Debug, Deserialize, Serialize)]
    pub struct StaticObj(pub std::collections::HashMap<String, serde_json::Value>);
    impl std::ops::Deref for StaticObj {
        type Target = std::collections::HashMap<String, serde_json::Value>;
        fn deref(&self) -> &Self::Target {
            &self.0
        }
    }
```

I think it's probable that the OpenAPI spec here is not great, but the code generated in this kinda circumstance is rather annoying to work with as well.

**Comment by jsenkpiel-godaddy** [comment]
Yeah ok this is definitely solvable on our end by making our spec specify wildcard values correctly (i.e. `{}` in OpenAPI), but I feel like it may be good to be able to configure the output of `object` to be `serde_json::Map` instead of `HashMap`.

**Comment by ahl** [comment]
I like the idea of using `serde_json::Map` instead of `HashMap` in particular for `serde_json::Map<String, serde_json::Value>`. I think `HashMap` may still be appropriate and preferable for APIs that don't otherwise end up using `serde_json::Value`.
