### ISSUE TITLE
`Accept` header is not set

### ISSUE THREAD

**Issue by provokateurin** [oxidecomputer/progenitor#375]
My API returns either XML or JSON based on the Accept header. It defaults to XML and since this library doesn't set the `Accept` header for requests all my requests fail because it can't parse the XML.

**Comment by ahl** [comment]
Can you work around this by using `request::ClientBuilder::default_headers()` to create a client with that set? Agreed that generated clients should include this header.

**Comment by provokateurin** [comment]
I did that in the end, just wanted to report this is not working properly.
