### ISSUE TITLE
progenitor-produced Cargo.toml is a workspace root?

### ISSUE THREAD

**Issue by jclulow** [oxidecomputer/progenitor#38]
It seems like #26 (I think?) introduced an empty `[workspace]` section to the generated `Cargo.toml`:

https://github.com/oxidecomputer/progenitor/blob/75348207d7405db3371a98b5348bef3fbd0ef79e/progenitor/src/main.rs#L93-L94

Is that intentional?  It confuses `cargo build` at least, when used to generate a crate that is already within a workspace:

```
$ cargo build
error: multiple workspace roots found in the same workspace:
  /ws/lux/keeper/openapi
  /ws/lux/keeper
```

**Comment by ahl** [comment]
It was intentional... but only to navigate around a common problem I was hitting with testing. Is this `openapi` crate enumerated within the workspace in `lux` or `keeper`?

**Comment by jclulow** [comment]
Yes, I generally stick it in; e.g., for buildomat:

```toml
[workspace]
members = [
        "agent",
        "bunyan",
        "client",
        "common",
        "factory/aws",
        "factory/lab",
        "github/common",
        "github/database",
        "github/dbtool",
        "github/ghtool",
        "github/server",
        "openapi",
        "server",
]
```
