### ISSUE TITLE
generated crate should probably globally allow unused code

### ISSUE THREAD

**Issue by jclulow** [oxidecomputer/progenitor#39]
Prior to #26 I think we used to emit `#[allow(dead_code)]` on a few of the support bits so that there aren't warnings when they're not used.  I think it might have gotten lost in the translation, so now I'm seeing:

```
warning: constant is never used: `PATH_SET`
   --> openapi/src/progenitor_client.rs:226:1
    |
226 | / const PATH_SET: &percent_encoding::AsciiSet = &percent_encoding::CONTROLS
227 | |     .add(b' ')
228 | |     .add(b'"')
229 | |     .add(b'#')
...   |
234 | |     .add(b'{')
235 | |     .add(b'}');
    | |_______________^
    |
    = note: `#[warn(dead_code)]` on by default

warning: function is never used: `encode_path`
   --> openapi/src/progenitor_client.rs:238:8
    |
238 | pub fn encode_path(pc: &str) -> String {
    |        ^^^^^^^^^^^

warning: `keeper-openapi` (lib) generated 2 warnings
```

Perhaps we should just add a global `#![allow(dead_code)]` to the top of the crate root (i.e., `src/lib.rs`)?  That seems to make the warnings go away for me at least.

**Comment by ahl** [comment]
It looks like you're using progenitor in the mode where it emits the crate source, is that right? Can you try just adding `#![allow(dead_code)]` to `openapi/src/progenitor_client.rs`? I moved e.g. `encode_path` into its own support crate, but didn't  consider the case where we were splatting it down into a file.
