### ISSUE TITLE
evolving APIs with #[serde(default)]

### ISSUE THREAD

**Issue by jclulow** [oxidecomputer/progenitor#41]
As I add more features to buildomat, I am trying to keep the API backwards compatible.  In particular, I sometimes add to POST bodies new booleans that default to a false value if missing, or arrays of values that default to empty if omitted.  I think this works well for arrays today, which appear to come out thus:

* On the Dropshot side:
    ```diff
     #[derive(Deserialize, JsonSchema)]
     pub(crate) struct JobSubmit {
         name: String,
         target: String,
         output_rules: Vec<String>,
         tasks: Vec<TaskSubmit>,
         #[serde(default)]
         inputs: Vec<String>,
         #[serde(default)]
         tags: HashMap<String, String>,
    +    #[serde(default)]
    +    depends: Vec<DependSubmit>,
     }
    ```
* On the Progenitor side:
    ```diff
         #[derive(Serialize, Deserialize, Debug, Clone)]
         pub struct JobSubmit {
    +        #[serde(default, skip_serializing_if = "Vec::is_empty")]
    +        pub depends: Vec<DependSubmit>,
             #[serde(default, skip_serializing_if = "Vec::is_empty")]
             pub inputs: Vec<String>,
             pub name: String,
    ```

For `bool` though, it currently emits an `Option<bool>`:

* On the Dropshot side:
    ```diff
     #[derive(Deserialize, JsonSchema)]
     pub(crate) struct FactoryWorkerCreate {
         target: String,
         job: Option<String>,
    +    #[serde(default)]
    +    wait_for_flush: bool,
     }
    ```
* On the Progenitor side:
    ```diff
         #[derive(Serialize, Deserialize, Debug, Clone)]
         pub struct FactoryWorkerCreate {
             #[serde(default, skip_serializing_if = "Option::is_none")]
             pub job: Option<String>,
             pub target: String,
    +        #[serde(default, skip_serializing_if = "Option::is_none")]
    +        pub wait_for_flush: Option<bool>,
         }

    ```

It's possible I'm holding it wrong, but I have not been able to figure out how to express the desire for a `bool` that has a default value on the Dropshot side, but is not then an `Option<bool>` on the Progenitor side.  I'm also not sure if there is a question here about types in general, or if this is specifically a `bool` wart.

I think what I want is just a bare `bool` with `#[serde(default)]` on the client side?  The server would default it to `false` if it is missing for old clients, but new clients would need to specify it on way or another.

**Comment by ahl** [comment]
fixed by #50
