### ISSUE TITLE
With replace, progenitor should only generate types that are reachable from an API it generates

### ISSUE THREAD

**Issue by sunshowers** [oxidecomputer/progenitor#426]
Consider what happens with a dropshot endpoint like:

```rust
struct MyTypedBody {
    inner: InnerType,
}

struct InnerType { ... }

#[endpoint { ... } ]
fn my_endpoint(..., body: TypedBody<MyTypedBody>) -> ... { }
```

If replace is used to not generate `MyTypedBody`, progenitor still generates `InnerType` even though nothing uses it. That seems unnecessary.

I think the algorithm progenitor should use is to construct a graph of which types depend on which other ones, and only generate type definitions for types that are reachable from one of the top-level types (roots of the graph). In this case, `MyTypedBody` is a root of the type graph because one of the HTTP methods uses it. If `MyTypedBody` isn't generated, anything that's only reachable from it shouldn't be generated either.

**Comment by ahl** [comment]
Dup of #177
