### ISSUE TITLE
Next release after 0.2.0

### ISSUE THREAD

**Issue by jayvdb** [oxidecomputer/progenitor#428]
Latest release is v0.2.0 - 7 months old.

Now that typify has been released, is there a plan for what is needed before the next progenitor release?

We are happily using "main", publishing it to cloudsmith.io so that we can use it as a build-dependency of our own crates, so IMO the current codebase is ready ;-)  But I am happy to help with features needed to get a new release onto crates.io .

For those without a cloudsmith, it would be good to start publishing alphas to crates.io

**Comment by jayvdb** [comment]
As progenitor is already using typify `main` features not yet released, perhaps we could have a feature `typify_0_0_11` or `typify_main` and new code using that needs to be feature flagged?

**Comment by jayvdb** [comment]
I've created https://github.com/franklin-ai/progenitor/tree/revert-to-typify-0_0_11 to have a branch that only uses typify-0.0.11 , and removes use of `typify-macro` and includes https://github.com/oxidecomputer/progenitor/pull/368 to remove the rustfmt-wrapper dependency.

**Comment by ahl** [comment]
I was hoping to get the CLI stuff in slightly better shape before the next progenitor release. If you'd like it sooner than that, I can cut a new release of typify and progenitor this weekend; I don't think it's that helpful to feature flag stuff.

**Comment by jayvdb** [comment]
We have cloudsmith so we're not needing a rushed release.  That said, it will be better for our SBOM and our devsecops audits to be not using our own fork.  If a release is coming in the next few weeks, that will be great!  If you need help to get features built, or docs written, etc, let me know and we'll try to help.

**Comment by jayvdb** [comment]
It would be good to advertise the next release in https://github.com/rust-lang/this-week-in-rust .

**Comment by ahl** [comment]
I'll leave that to you after I cut the release. Thanks!

**Comment by ahl** [comment]
The API has become a bit of a garbage barge. It would be nice to start cleaning that up, but I'll try to find a 0.3.0 ASAP

**Comment by ahl** [comment]
https://crates.io/crates/progenitor/0.3.0

**Comment by jayvdb** [comment]
I've proposed progenitor to be in This Week in Rust at https://users.rust-lang.org/t/crate-of-the-week/2704/1200

**Comment by jayvdb** [comment]
@ahl expect incoming... https://this-week-in-rust.org/blog/2023/05/31/this-week-in-rust-497/#crate-of-the-week
