### ISSUE TITLE
Publishing to crates.io?

### ISSUE THREAD

**Issue by erikh** [oxidecomputer/progenitor#43]
I love this library. It fixes a ton of issues I could not get around in the openapi generator.

I have a few open pull requests (https://github.com/zerotier/zerotier-rust-api/pull/1 and https://github.com/zerotier/zeronsd/pull/186) that would allow me to leverage this library but because I cannot publish crates which depend on progenitor I cannot proceed.

I can deal with it, but it would be nice to know if or when you plan on publishing?

**Comment by erikh** [comment]
I should also add that within reason, I can assist with helping you get "over the hump" regarding any goals if you have a list of things that need to be done.

**Comment by ahl** [comment]
Thanks for the kind words. I've been waiting for it to be relatively stable to publish it, but I think it's gotten there now. I'll get it published within 2 weeks if that works for you.

**Comment by erikh** [comment]
Sure that's great news! Thanks.

------- Original Message -------

**Comment by ahl** [comment]
Clearly much to be improve (a README perhaps) but it's there: https://crates.io/crates/progenitor

**Comment by erikh** [comment]
oh awesome! Thank you! I'll get to integrating this soon
