### ISSUE TITLE
Github tag for 0.4.0 missing

### ISSUE THREAD

**Issue by jayvdb** [oxidecomputer/progenitor#634]
progenitor 0.4.0 has been released to crates.io, but there is no tag at https://github.com/oxidecomputer/progenitor/tags

Looks like https://github.com/oxidecomputer/progenitor/commit/73087a37fdbf195922b56dbdc89ca44a3031ef52 was the commit for v0.4.0

**Comment by ahl** [comment]
Thanks; pushed!
