### ISSUE TITLE
OpenAPI "date" type results in chrono::Date instead of chrono::NaiveDate

### ISSUE THREAD

**Issue by willfindlay** [oxidecomputer/progenitor#716]
See title. The `chrono::Date` type is deprecated and does not even include a serlialize/deserialize implementation. I would have expected `NaiveDate` instead.

**Comment by ahl** [comment]
I thought we fixed this in #434 -- what version are you running?

**Comment by matoous** [comment]
I think this needs change in [typify](https://github.com/oxidecomputer/typify):
```diff
diff --git i/typify-impl/src/convert.rs w/typify-impl/src/convert.rs
index f3cb022..974eb99 100644
--- i/typify-impl/src/convert.rs
+++ w/typify-impl/src/convert.rs
@@ -719,7 +719,7 @@ impl TypeSpace {
                 self.uses_chrono = true;
                 Ok((
                     TypeEntry::new_native(
-                        "chrono::Date<chrono::offset::Utc>",
+                        "chrono::NaiveDate",
                         &[TypeSpaceImpl::Display, TypeSpaceImpl::FromStr],
                     ),
                     metadata,
```

**Comment by matoous** [comment]
Here's a PR: https://github.com/oxidecomputer/typify/pull/510, not sure if it's that easy though as it would require updates by whomever relies on the generated code. On the other hand, given `chrono::Date` is deprecated this seems inevitable at some point.

**Comment by ahl** [comment]
Feel free to re-open if this is still an issue
