### ISSUE TITLE
Thread Panic when running Static Crate

### ISSUE THREAD

**Issue by NovaLogicDev** [oxidecomputer/progenitor#723]
```sh
thread '<unnamed>' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustfmt-wrapper-0.2.0/src/lib.rs:89:14:
Failed to write to stdin: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-progenitor-0.4.1/src/main.rs:101:68:
called `Result::unwrap()` on an `Err` value: Unstable("wrap_comments, normalize_doc_attributes")
```

Command used
`cargo progenitor -i ./swagger.json -o edfi-client -v 1.0 -n EdfiClient --interface builder`

other commands tested
`cargo progenitor -i ./swagger.json -o edfi-client -v 1.0 -n EdfiClient`

The swagger spec being used can be found here: 
https://[api.ed-fi.org/v5.1.0/api/metadata/data/v3/resources/swagger.json](https://api.ed-fi.org/v5.1.0/api/metadata/data/v3/resources/swagger.json)

Converted to OpenApi3.0 with https://editor-next.swagger.io/

Tried running on Windows and WSL2:Ubuntu

**Comment by ahl** [comment]
Looks like another case of an old swagger/OpenAPI version: `"swagger":"2.0"`

Progenitor **really** needs to do some checking before it barfs like this.

**Comment by NovaLogicDev** [comment]
even though I ran the spec through the open API converter first?

**Comment by ahl** [comment]
Sorry: poor reading comprehension over here. Can you post the output of the conversion tool somewhere? Thank you!

**Comment by NovaLogicDev** [comment]
[openapi3_0.json](https://github.com/oxidecomputer/progenitor/files/14300463/openapi3_0.json)

**Comment by ahl** [comment]
Ah. Make sure rustfmt nightly is installed.

**Comment by NovaLogicDev** [comment]
I'm not sure I follow, is there a way to not use unstable things?

**Comment by NovaLogicDev** [comment]
I just ran with the nightly toolchain and it is working at least.

**Comment by NovaLogicDev** [comment]
The output won't compile though:

```bash
Compiling EdfiClient v1.0.0 (/home/max_paulson/client/RustyEdfiClient)
error: unexpected closing delimiter: `}`
--> src/lib.rs:293277:5
             |
293133 |     impl<'a> KeyChangesEducationOrganizationInterventionPrescriptionAssociations<'a> { 
             |                                                                                                                                                 - this delimiter might not be properly closed...                                                                                                  ...                                                                                                                     293276 |         }                                                                                                             
             |         - ...as it matches this but it has different indentation                                               
293277 |     }                                                                                                                 
             |     ^ unexpected closing delimiter
error: could not compile `EdfiClient` (lib) due to 1 previous error
```

[RustyEdfiClient.zip](https://github.com/oxidecomputer/progenitor/files/14301430/RustyEdfiClient.zip)

**Comment by ahl** [comment]
Excellent. Thank you for this; I'll take a look and see what's going on.

**Comment by NovaLogicDev** [comment]
Wanted to circle back to this, I tried using the Macro instead of generating a static crate, it appears to compile okay, but the builder interface seems out of line with the documentation, and more noteworthy is that build times have drastically increased, usually several minutes or longer.

**Comment by ahl** [comment]
That's vexing. The static crate and macro should be the same code. Thanks for the ping; I'll take a look now.

**Comment by ahl** [comment]
The contents of the zip file seem to have been generated from some different OpenAPI document. In particular, I don't see the `/ed-fi/educationOrganizationInterventionPrescriptionAssociations/keyChanges` path that was related to the error above.

> the builder interface seems out of line with the documentation

Is this documentation in a readme or generated docs?

> build times have drastically increased, usually several minutes or longer

It does emit a 300k LOC lib.rs (almost 400k LOC in the zip file) so that's probably going to take time to compile. I don't know that I have a good remedy. One option is to prune the OpenAPI document, but that's not a great solution.

**Comment by NovaLogicDev** [comment]
I've done some more digging.

The original compilation error appears to just occur if I try to generate a builder style output, through macro, build.rs or static crate. I was able to reduce the build times by switching to using build.rs and by not using the builder style the code length comes down to just under 10mb. 

As for the documentation, I'm talking about the readme, and after some coffee it became clear to me the samples at the end assume you have created a client already (even thought that part doesn't seem to be covered), it was also just unclear to me that things like "instance_create" were actually sample HTTP endpoints and that function is part of the generated code.

**Comment by ahl** [comment]
> I've done some more digging.

Thanks!

> The original compilation error appears to just occur if I try to generate a builder style output, through macro, build.rs or static crate. I was able to reduce the build times by switching to using build.rs and by not using the builder style the code length comes down to just under 10mb.

Can you send the OpenAPI doc you're using? Again, I think the one you posted earlier doesn't manifest the problem we're discussing.

> As for the documentation, I'm talking about the readme, and after some coffee it became clear to me the samples at the end assume you have created a client already (even thought that part doesn't seem to be covered), it was also just unclear to me that things like "instance_create" were actually sample HTTP endpoints and that function is part of the generated code.

Thanks for that. We should update the README and describe the multiple methods of generation (I've been trying to migrate from the positional method to the builder one as the default).

**Comment by NovaLogicDev** [comment]
I'm going to continue with this thread and add this fun error I'm having now, there are a few hundred of them, all about the same. rust claiming that there are duplicate definitions but citing the same lines of code for both candidates.

Here's the output rs file, same input as my previous comment, copied the buildscript code from the documentation.

[codegen.rs.txt](https://github.com/oxidecomputer/progenitor/files/14504437/codegen.rs.txt)

```rust
error[E0034]: multiple applicable items in scope
      --> src\codegen.rs:191667:15
       |
191667 |         Self::new_with_client(baseurl, client.build().unwrap())
       |               ^^^^^^^^^^^^^^^ multiple `new_with_client` found
       |
note: candidate #1 is defined in an impl for the type `Client`
      --> src\codegen.rs:191675:5
       |
191675 |     pub fn new_with_client(baseurl: &str, client: reqwest::Client) -> Self {
       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in an impl for the type `Client`
      --> src\codegen.rs:191675:5
       |
191675 |     pub fn new_with_client(baseurl: &str, client: reqwest::Client) -> Self {
       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       ```

**Comment by Torsitano** [comment]
Stumbled on this trying to use Progenitor today and am experiencing the same thing. Macro and static crate both panic, even when run with nightly.

Any updates on a fix or workaround?

```shell
$ rustc --version
rustc 1.79.0-nightly (fb898629a 2024-04-21)


$ RUST_BACKTRACE=full cargo progenitor -i build/schema.json -o progenitor -n jira-rs -v 0.1
thread 'main' panicked at /home/shawn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/typify-impl-0.0.16/src/merge.rs:268:70:
called `Result::unwrap()` on an `Err` value: ()
stack backtrace:
   0:     0x55c2b377f836 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
   1:     0x55c2b37aa330 - core::fmt::write::he40921d4802ce2ac
   2:     0x55c2b377c92f - std::io::Write::write_fmt::h5de5a4e7037c9b20
   3:     0x55c2b377f614 - std::sys_common::backtrace::print::h11c067a88e3bdb22
   4:     0x55c2b3780ce7 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
   5:     0x55c2b3780a49 - std::panicking::default_hook::h1633e272b4150cf3
   6:     0x55c2b3781178 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
   7:     0x55c2b3781052 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
   8:     0x55c2b377fd36 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
   9:     0x55c2b3780da4 - rust_begin_unwind
  10:     0x55c2b321c275 - core::panicking::panic_fmt::ha6effc2775a0749c
  11:     0x55c2b321c7c3 - core::result::unwrap_failed::ha188096f98826595
  12:     0x55c2b353024b - typify_impl::convert::<impl typify_impl::TypeSpace>::convert_schema_object::h29673106cf71ac73
  13:     0x55c2b352d78e - typify_impl::convert::<impl typify_impl::TypeSpace>::convert_schema::hb82a0713ecd6c702
  14:     0x55c2b353cac6 - typify_impl::TypeSpace::convert_ref_type::h4e9dec0ddad51b7b
  15:     0x55c2b33f749a - typify_impl::TypeSpace::add_ref_types::h4bda4ec3229bfd94
  16:     0x55c2b3398aa5 - progenitor_impl::Generator::generate_tokens::h7f97368c8530a754
  17:     0x55c2b32bf842 - cargo_progenitor::main::hfcf7fd325959a141
  18:     0x55c2b331eee3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hee22a5ad8de69ae3
  19:     0x55c2b32c89dd - std::rt::lang_start::{{closure}}::h0ee7cb12518ff3c6
  20:     0x55c2b3775611 - std::rt::lang_start_internal::h4d236095b69a230b
  21:     0x55c2b32c6925 - main
  22:     0x7f8b6915fd90 - <unknown>
  23:     0x7f8b6915fe40 - __libc_start_main
  24:     0x55c2b321cac5 - _start
  25:                0x0 - <unknown>
  ```

**Comment by ahl** [comment]
This looks like potentially a different issue. Can you please open a new issue and include the input OpenAPI document?

**Comment by ahl** [comment]
> [edfi.json](https://github.com/oxidecomputer/progenitor/files/14450831/edfi.json)

I tried this today with main, and the generated code is compiling. I did encounter a missing dependency (#788) and some odd behavior with rustfmt where it's greedily adding code into comments (thus making the code not work).

@NovaLogicDev I'm going to close this issue; please let me know if you're still hitting problems.

**Comment by ahl** [comment]
This is the rustfmt issue for reference: https://github.com/rust-lang/rustfmt/issues/3988
