### ISSUE TITLE
Ability to set default headers

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/progenitor#81]
Currently the generated code doesn't deal with request headers. To add default headers to all requests, you would have to write some sort of wrapper function separately.

It could be pretty useful to be able to have the ability to set these default headers through the `build.rs` file. We can leverage the [`default_headers`](https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.default_headers) method when constructing the `Client`.

```rust
let mut headers = reqwest::header::HeaderMap::new();
headers.insert(reqwest::header::AUTHORIZATION, auth_value);
// insert more headers

let client = reqwest::ClientBuilder::new()
    .connect_timeout(dur)
    .timeout(dur)
    .default_headers(headers) // Add this line to the generated code
    .build()
    .unwrap();
Self::new_with_client(baseurl, client)
```

**Comment by ahl** [comment]
Is this already covered by `Client::new_with_client()`?

**Comment by karencfv** [comment]
Should have removed this PR when we had a chat the other time, sorry! Btw, this might not be so obvious from the README. Do you mind if I add some documentation around this?

**Comment by ahl** [comment]
Any documentation you could add would be delightful! Thank you!
