### ISSUE TITLE
Add a `try_new` option on `Client`

### ISSUE THREAD

**Issue by mpekala23** [oxidecomputer/progenitor#836]
It would be nice if there were a way to construct `Client` without the hidden `unwrap` that happens on the `ClientBuilder`. You can accomplish this manually by simply checking for error on the `ClientBuilder` yourself and then using `new_with_client`, but it could be nice if this was encapsulated in some `try_new` method.

**Comment by ahl** [comment]
Is it possible for that `unwrap` to fail? If not, a `try_new` seems unnecessarily complicated. If it can, perhaps `new` should return a `Result`.

**Comment by mpekala23** [comment]
Just reviewed this again and you're right. For a second I thought this unwrap would fail if the url the client pointed to couldn't be reached but that's incorrect. I agree that `try_new` / `result` is unnecessarily complex. Thanks for taking a look!
