### ISSUE TITLE
Panic while generating BNA API

### ISSUE THREAD

**Issue by rgreinho** [oxidecomputer/progenitor#877]
I am trying to generate a client for the [BNA API](https://github.com/PeopleForBikes/bna-api/blob/main/openapi.yaml), and I am getting a very generic error which does not help me spotting the value causing the issue.

```bash 
$ RUST_BACKTRACE=1 cargo progenitor -i openapi.yaml -o bnaclient -n bnaclient -v 1.0.0 --interface builder

gen fail: TypeError(InvalidValue)
Error: generation experienced errors

Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: anyhow::error::<impl anyhow::Error>::msg
   2: cargo_progenitor::main
   3: std::sys_common::backtrace::__rust_begin_short_backtrace
   4: std::rt::lang_start::{{closure}}
   5: std::rt::lang_start_internal
   6: _main
```

The file does not generate any error in the [Swagger editor](https://editor.swagger.io/).

**Comment by dunxen** [comment]
I get the same error in #955, and I'm not sure if they might miraculously be related.

**Comment by mkatychev** [comment]
Running with `RUST_LOG=debug` will give more information here, this gave an easy fix here: https://github.com/PeopleForBikes/bna-api/pull/146.

**Comment by dunxen** [comment]
Ah, didn't know the logging was set up. Should have tried that for my issue. Thanks!

**Comment by rgreinho** [comment]
We got it to work by tweaking the openapi.yaml file 👍
