### ISSUE TITLE
Generator::httpmock fails with a confusing error when provided crate_name contains hyphen

### ISSUE THREAD

**Issue by ewancg** [oxidecomputer/progenitor#984]
When using progenitor to generate a statically typed httpmock extension, someone might be tempted to put a hyphen inside their crate name:
```rs
generator.httpmock(&spec, "something-mock")
```
This will work for many use cases because package names with hyphens are automatically converted to have underscores, thanks to the fact that hyphens are not valid characters in Rust identifiers. In the case of progenitor, it will fail like so:
```
called `Result::unwrap()` on an `Err` value: Error("unexpected token")
```
because, presumably, `something` and `mock`  are being interpreted as separate identifiers. There's nothing untrue about this error per se, but it really did confuse me until I realized what was actually going on. Perhaps this edge-case should be caught and error explicitly.

**Comment by ahl** [comment]
Thank you; that's a terrible UX.

**Comment by ewancg** [comment]
Thanks for the fix!
