### ISSUE TITLE
Support Generating IndexMap Instead of HashMap

### ISSUE THREAD

**Issue by JosiahBull** [oxidecomputer/progenitor#985]
For some usecases, e.g. snapshots in tests, consistent ordering via `IndexMap` would be preferred over a randomly ordered `HashMap` in generated clients.

I am happy to do the work required to allow users of the `progenitor` library to opt-in to this feature via a feature flag or as the default. I can alternatively extend support this feature via the `x-rust-type` mechanism, with a special case when `path` is equal to `indexmap::IndexMap` or `indexmap::IndexSet` to enable this feature.

Let me know if this is in-scope for the features you'd like `progenitor` to support and I'll open a PR. 👍

**Comment by JosiahBull** [comment]
Just found this related issue: https://github.com/oxidecomputer/typify/issues/555

Would support be welcome all the way through into Progenitor, or only in Typify?

**Comment by ahl** [comment]
For sure. Plumb it right on through!
